browser=chrome
url=https://www.facebook.com/
compatibility=mac

#urls
GoogleHomePageTest=https://www.google.com
FaceBookSignupPageTest=https://www.facebook.com
FacebookLoginPageTest=https://www.facebook.com
BasicCLTest=https://rahulshettyacademy.com/AutomationPractice/
datatable=https://datatables.net/
CrexPageTest=https://crex.com/
BasicTestClass=https://crex.com/